// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geqvuttwlpnsnquawxdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlcXZ1dHR3bHBuc25xdWF3eGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MDg0NDUsImV4cCI6MjA1MDk4NDQ0NX0.vcUIWPslztb8iJVZ6YS05Un1uhCn8kup-h8MEpz0vGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);